#!/bin/bash -e
#SBATCH --account massey03212
#SBATCH --job-name Campy_unmap_Orion
#SBATCH --time 12:00:00
#SBATCH --mem 6GB
#SBATCH --cpus-per-task 14
#SBATCH --error %x_%j.err
#SBATCH --output %x_%j.out

# Load necessary modules
module purge
module load SAMtools/1.21-GCC-12.3.0
module load Bowtie2/2.5.4-GCC-12.3.0

# --- 1. SET GLOBAL VARIABLES ---
BASE_DIR="/nesi/nobackup/massey03212/Nat_comms/Genomic_analysis/15_mapping_experiment/10_C_jejuni_investigation/orion_mapping"
READS_DIR="/nesi/nobackup/massey03212/Nat_comms/Genomic_analysis/15_mapping_experiment/10_C_jejuni_investigation/orion_mapping/individual_mapped_results_orion/unmapped_reads" # Input FASTQ files are here (.fastq)
INDEX_BASE="/nesi/nobackup/massey03212/Nat_comms/Genomic_analysis/15_mapping_experiment/02_References/for_humans"
OUTPUT_DIR="${BASE_DIR}/individual_unmapped_to_jeju_orion"
COUNT_FILE="${OUTPUT_DIR}/species_unmapped_to_jeju_individual.tsv"

# Define Target Species (C_infans and C_sp900 only)
declare -A SPECIES_INDICES
SPECIES_INDICES["C_jejuni"]="${INDEX_BASE}/C_jejuni_index"
SPECIES_INDICES["C_coli"]="${INDEX_BASE}/C_coli_index"

# Define the file suffixes based on the input file structure (ugXXX_hostFilt_R1.fastq)
R1_SUFFIX="_unmapped_R1.fastq"
R2_SUFFIX="_unmapped_R2.fastq"

# Create output directories and subdirectories for mapped/unmapped reads
mkdir -p "$OUTPUT_DIR"
mkdir -p "${OUTPUT_DIR}/mapped_reads"
mkdir -p "${OUTPUT_DIR}/unmapped_reads"

echo "--- Starting Individual Mapping and Counting for Orion Files ---"

# Initialize the output file with a header
echo -e "Sample\tC_jejuni_Count\tC_coli_Count" > "$COUNT_FILE"

# --- 2. MAIN LOOP: Process each sample (FASTQ file pair) ---

# Find all unique sample IDs based on R1 files, using the CORRECT suffix.
SAMPLES=$(find "${READS_DIR}" -maxdepth 1 -name "*${R1_SUFFIX}" -type f | \
    xargs -n 1 basename | \
    sed "s/${R1_SUFFIX}//" | \
    sort -u)

if [ -z "$SAMPLES" ]; then
    echo "❌ ERROR: No matching R1 files found in $READS_DIR. Exiting."
    exit 1
fi

for sample in $SAMPLES; do
    # Define the paired-end file paths (uncompressed input)
    R1="${READS_DIR}/${sample}${R1_SUFFIX}"
    R2="${READS_DIR}/${sample}${R2_SUFFIX}"
    
    # Check for file existence
    if [ ! -f "$R1" ] || [ ! -f "$R2" ]; then
        echo "❌ ERROR: Paired files not found for sample $sample. Skipping."
        continue
    fi
    
    echo "Processing sample: $sample"
    OUTPUT_LINE="$sample"
    
    # --- 3. SPECIES LOOP: Map and Count for each species ---
    for species in "${!SPECIES_INDICES[@]}"; do
        INDEX="${SPECIES_INDICES[$species]}"
        BAM_OUTPUT="${OUTPUT_DIR}/${sample}_${species}.bam"
        
        # Output file paths for MAPPED and UNMAPPED reads (NO .gz suffix)
        MAPPED_R1="${OUTPUT_DIR}/mapped_reads/${sample}_${species}_mapped_R1.fastq"
        MAPPED_R2="${OUTPUT_DIR}/mapped_reads/${sample}_${species}_mapped_R2.fastq"
        UNMAPPED_R1="${OUTPUT_DIR}/unmapped_reads/${sample}_${species}_unmapped_R1.fastq"
        UNMAPPED_R2="${OUTPUT_DIR}/unmapped_reads/${sample}_${species}_unmapped_R2.fastq"
        
        # Temporary file names generated by Bowtie 2
        TEMP_UNMAPPED_1="${OUTPUT_DIR}/unmapped_reads/${sample}_${species}_unmapped_1.fastq"
        TEMP_UNMAPPED_2="${OUTPUT_DIR}/unmapped_reads/${sample}_${species}_unmapped_2.fastq"

        echo "  -> Mapping to $species index..."

        # Bowtie2 command: uses --un-conc for uncompressed output
        bowtie2 \
            --minins 200 \
            --maxins 800 \
            --threads "$SLURM_CPUS_PER_TASK" \
            --sensitive \
            --un-conc "${OUTPUT_DIR}/unmapped_reads/${sample}_${species}_unmapped_%.fastq" \
            -x "$INDEX" -1 "$R1" -2 "$R2" | \
            samtools view -@ "$SLURM_CPUS_PER_TASK" -b -h -F 4 - \
            > "$BAM_OUTPUT"
        
        # Convert the BAM file (MAPPED reads only) to UNCOMPRESSED FASTQ (No -z flag)
        echo "  -> Extracting MAPPED reads (output is uncompressed)..."
        samtools fastq -@ "$SLURM_CPUS_PER_TASK" -f 3 -1 "$MAPPED_R1" -2 "$MAPPED_R2" "$BAM_OUTPUT"

        # Counting the reads
        species_count=$(samtools view -c "$BAM_OUTPUT")
        
        echo "  - $species Mapped Reads: $species_count"
        OUTPUT_LINE="${OUTPUT_LINE}\t${species_count}"
        
        # Rename the unmapped files generated by Bowtie 2
        echo "  -> Renaming UNMAPPED reads..."
        
        mv "$TEMP_UNMAPPED_1" "$UNMAPPED_R1"
        mv "$TEMP_UNMAPPED_2" "$UNMAPPED_R2"
        
        # Optional: remove the BAM file after extraction to save space
        # rm "$BAM_OUTPUT"
    done
    
    # --- 4. WRITE RESULTS ---
    echo -e "$OUTPUT_LINE" >> "$COUNT_FILE"
done

echo "---"
echo "Script finished successfully. 🎉"
echo "Final counts are in: $COUNT_FILE"
echo "Mapped reads are in: ${OUTPUT_DIR}/mapped_reads/"
echo "Unmapped reads are in: ${OUTPUT_DIR}/unmapped_reads/"
