#!/bin/bash -e
#SBATCH --account massey03212
#SBATCH --job-name C_je_agrf_exp_human
#SBATCH --time 92:00:00
#SBATCH --mem 6GB
#SBATCH --cpus-per-task 14
#SBATCH --error %x_%j.err
#SBATCH --output %x_%j.out

# Load necessary modules
module purge
module load SAMtools/1.21-GCC-12.3.0
module load Bowtie2/2.5.4-GCC-12.3.0

# --- 1. SET GLOBAL VARIABLES ---
BASE_DIR="/nesi/nobackup/massey03212/Nat_comms/Genomic_analysis/15_mapping_experiment/10_C_jejuni_investigation/agrf_mapping"
READS_DIR="${BASE_DIR}/human_files_agrf" # Input FASTQ files are here
INDEX_BASE="/nesi/nobackup/massey03212/Nat_comms/Genomic_analysis/15_mapping_experiment/02_References/for_humans"
OUTPUT_DIR="${BASE_DIR}/individual_mapped_results"
COUNT_FILE="${OUTPUT_DIR}/species_read_counts_final_individual.tsv"

# Define Target Species and their index prefixes (Updated to exclude C_jejuni and C_coli)
declare -A SPECIES_INDICES
SPECIES_INDICES["C_infans"]="${INDEX_BASE}/C_infans_index"
SPECIES_INDICES["C_sp900"]="${INDEX_BASE}/C_sp900_index"

# Create output directories and subdirectories for mapped/unmapped reads
mkdir -p "$OUTPUT_DIR"
mkdir -p "${OUTPUT_DIR}/mapped_reads"
mkdir -p "${OUTPUT_DIR}/unmapped_reads"

echo "--- Starting Individual Mapping and Counting ---"

# Initialize the output file with a header (Updated header)
echo -e "Sample\tC_infans_Count\tC_sp900_Count" > "$COUNT_FILE"

# --- 2. MAIN LOOP: Process each sample (FASTQ file pair) ---

# Find all unique sample IDs based on R1 files, assuming the consistent '_hostFilt.fastq.gz' suffix.
SAMPLES=$(find "${READS_DIR}" -maxdepth 1 -name '*_R1_hostFilt.fastq.gz' -type f | \
    xargs -n 1 basename | \
    sed 's/_R1_hostFilt.fastq.gz//' | \
    sort -u)

if [ -z "$SAMPLES" ]; then
    echo "❌ ERROR: No '_hostFilt.fastq.gz' files found in $READS_DIR. Exiting."
    exit 1
fi

for sample in $SAMPLES; do
    # Define the paired-end file paths using the consistent suffix
    R1="${READS_DIR}/${sample}_R1_hostFilt.fastq.gz"
    R2="${READS_DIR}/${sample}_R2_hostFilt.fastq.gz"
    
    # Check for file existence
    if [ ! -f "$R1" ] || [ ! -f "$R2" ]; then
        echo "❌ ERROR: Paired host-filtered files not found for sample $sample. Skipping."
        continue
    fi
    
    echo "Processing sample: $sample"
    OUTPUT_LINE="$sample"
    
    # --- 3. SPECIES LOOP: Map and Count for each species ---
    for species in "${!SPECIES_INDICES[@]}"; do
        INDEX="${SPECIES_INDICES[$species]}"
        BAM_OUTPUT="${OUTPUT_DIR}/${sample}_${species}.bam"
        
        # Output file paths for MAPPED and UNMAPPED reads
        MAPPED_R1="${OUTPUT_DIR}/mapped_reads/${sample}_${species}_mapped_R1.fastq.gz"
        MAPPED_R2="${OUTPUT_DIR}/mapped_reads/${sample}_${species}_mapped_R2.fastq.gz"
        UNMAPPED_R1="${OUTPUT_DIR}/unmapped_reads/${sample}_${species}_unmapped_R1.fastq.gz"
        UNMAPPED_R2="${OUTPUT_DIR}/unmapped_reads/${sample}_${species}_unmapped_R2.fastq.gz"
        
        echo "  -> Mapping to $species index..."

        # Bowtie2 command: pipes output to SAMtools for BAM conversion and filtering.
        # --un-conc-gz outputs unaligned paired reads to the specified R1/R2 files.
        bowtie2 \
            --minins 200 \
            --maxins 800 \
            --threads "$SLURM_CPUS_PER_TASK" \
            --sensitive \
            --un-conc-gz "${OUTPUT_DIR}/unmapped_reads/${sample}_${species}_unmapped_%.fastq.gz" \
            -x "$INDEX" -1 "$R1" -2 "$R2" | \
            samtools view -@ "$SLURM_CPUS_PER_TASK" -b -h -F 4 - \
            > "$BAM_OUTPUT"
        
        # Convert the BAM file (containing only MAPPED reads, due to -F 4) to FASTQ
        echo "  -> Extracting MAPPED reads..."
        samtools fastq -@ "$SLURM_CPUS_PER_TASK" -f 3 -1 "$MAPPED_R1" -2 "$MAPPED_R2" "$BAM_OUTPUT"

        # Counting the reads from the BAM file (Mapped reads)
        species_count=$(samtools view -c "$BAM_OUTPUT")
        
        echo "  - $species Mapped Reads (Counted from BAM): $species_count"
        OUTPUT_LINE="${OUTPUT_LINE}\t${species_count}"
        
        # Rename the unmapped files generated by Bowtie 2 to a more specific naming scheme
        mv "${OUTPUT_DIR}/unmapped_reads/${sample}_${species}_unmapped_1.fastq.gz" "$UNMAPPED_R1"
        mv "${OUTPUT_DIR}/unmapped_reads/${sample}_${species}_unmapped_2.fastq.gz" "$UNMAPPED_R2"
        
        # Optional: remove the BAM file after extraction to save space
        # rm "$BAM_OUTPUT"
    done
    
    # --- 4. WRITE RESULTS ---
    echo -e "$OUTPUT_LINE" >> "$COUNT_FILE"
done

echo "---"
echo "Script finished successfully. 🎉"
echo "Final counts are in: $COUNT_FILE"
echo "Mapped reads are in: ${OUTPUT_DIR}/mapped_reads/"
echo "Unmapped reads are in: ${OUTPUT_DIR}/unmapped_reads/"
